[project]
name = "Decentralised_pred-market"
authors = []
description = ""
telemetry = true
requirements = []

[contracts.pred-market-v2-fixed]
path = "contracts/pred-market-v2-fixed.clar"
depends_on = []

# Original contract commented out due to compilation errors
# [contracts.Prediction_market-platform]
# path = "contracts/Prediction_market-platform.clar"
# depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
